### ISSUE TITLE
No way to call gst_base_parse_set_pts_interpolation on an Element?

### ISSUE THREAD

**Issue by pedrocr** [sdroege/gstreamer-sys#10]
I have an rtsp IP camera that `h264parse` doesn't grok completely and results in broken PTS on I-frames. This makes it so that `mp4mux` doesn't work at all and `matroskamux` just generates a broken file with no I-frames. It is probably this bug:

https://bugzilla.gnome.org/show_bug.cgi?id=788777

In this case it happens 100% of the time. I've found a workaround by using a feature of `GstBaseParse`:

https://gist.github.com/zougloub/0747f84d45bc35413c0c19584c398b3d/#file-dvr-py-L93-L94

But now I'm stuck on how to call `gst_base_parse_set_pts_interpolation` on the `h264parse` object. I don't see any path from the `Element` to a `*mut GstBaseParse`. Is this simply not packaged in any API?

**Comment by sdroege** [comment]
You can get an unowned `*mut GstElement` from the `Element` via [`ToGlibPtr::to_glib_none()`](http://gtk-rs.org/docs/glib/translate/trait.ToGlibPtr.html#tymethod.to_glib_none), which you can then cast to a `*mut GstBaseParse` via `as` and pass it to that function.

The `GstBaseParse` API is not covered by the safe bindings yet, but it's all available via `gstreamer-base-sys` like the C API.

**Comment by pedrocr** [comment]
Thanks! I'll try and get that working so I can attach a version of the probe output with the workaround enabled to the bug report.

**Comment by sdroege** [comment]
Let me know if you get stuck somewhere, ideally with the code you have up to that point :) then I'll try to help

**Comment by pedrocr** [comment]
Your description was enough after a little trial and error :)

```rust
  // Enable PTS interpolation to work around missing PTS on I-frame with at least some camera's
  // RTSP output
  unsafe {
    let el: *mut GstElement = parser.to_glib_none().0;
    gstreamer_base_sys::gst_base_parse_set_pts_interpolation(el as *mut GstBaseParse, 1);
  }
```

**Comment by sdroege** [comment]
Yes, that's correct. If you want to be even more correct, you can replace the `1` with `glib_ffi::GTRUE` (or `true.to_glib()`) but that doesn't really matter. Just nicer to read

**Comment by pedrocr** [comment]
Yeah, I though about that but when I followed the rabbit hole in the docs and saw that it ended up just being a c_int, 1 seemed good enough.
