### ISSUE TITLE
generate gstreamer-gl-sys

### ISSUE THREAD

**Issue by ceyusa** [sdroege/gstreamer-sys#13]
This is a subtask for https://github.com/sdroege/gstreamer-rs/issues/126

Some notes:

Regarding the question which gl bindings use, the answer is [gl-rs](https://github.com/brendanzab/gl-rs/), and more specifically, [gl_generator](https://github.com/brendanzab/gl-rs/blob/master/gl_generator/README.md), which creates customs GL bindings at build time. That's what [gleam](https://github.com/servo/gleam) uses.

When I want to generated the sys from GstGL-1.0.gir, no matter what `work-mode` I choose in Gir_GstGL.toml, the gir tool will always throw an exception:

```
GirXml: gir-files/GstGL-1.0.gir:3201:13: Missing type name
```

There are a lot of parameters types without name: all the GL related and xlib `Display` and `xcb_connection_t`. The later I solved them with `pointer` as name (perhaps we should handle that in the GstGL annotations), but the ones related with GL types are the problem.

As far as I have tinkered with `gir` I haven't found a way to workaround this. I even added fake names, but it breaks (obviously) later with 

```
thread 'main' panicked at 'Incomplete library, unresolved: ["GL.bitfield", "GL.boolean", "GL.char", "GL.clampf", "GL.eglImageOES", "GL.enum", "GL.float", "GL.int", "GL.int64", "GL.intptr", "GL.sizei", "GL.sizeiptr", "GL.sync", "GL.ubyte", "GL.uint", "GL.uint64"]', gir/src/library_postprocessing.rs:55:13
```

Those types should be resolved by gl_generater, but I haven't figured out how, and I'm suspecting that `gir` won't be usable and the bindings must be written by hand :sob:

**Comment by sdroege** [comment]
Did you try with `GL-1.0.gir` as a starting point? That should generate all the GL types in a meaningful way

**Comment by ceyusa** [comment]
Thanks @sdroege !  I didn't know the existence of GL-1.0.gir. Now I can generate  gstreamer-gl-sys with `gir`. Though it is not functional yet.

Here's my WIP branch:

https://github.com/sdroege/gstreamer-sys/compare/master...ceyusa:gst-gl-sys?expand=1

**Comment by ceyusa** [comment]
I have updated the binding removing GstGLFuncs from gir

I wonder if setting wayland structures and X11's Display can be set as gpointer :)

**Comment by sdroege** [comment]
IMHO they should not even be part of the .gir or bindings as they depend on compile-time configuration. Same for EGL and all the backend specific bits. They should be hidden at least behind feature flags.

Also `Display` is an `int` in X11 or not? :)

**Comment by ceyusa** [comment]
> IMHO they should not even be part of the .gir or bindings as they depend on compile-time configuration. Same for EGL and all the backend specific bits. They should be hidden at least behind feature flags.

OK. That should be done manually  perhaps.

> Also `Display` is an `int` in X11 or not? :)

it is a typedef of an opaque structure (_XDisplay). Thus, Display* is just a pointer.

**Comment by sdroege** [comment]
> OK. That should be done manually perhaps.

What do you suggest?

**Comment by ceyusa** [comment]
> What do you suggest?

Feature flags for X11, Wayland and EGL. Though Wayland will enable EGL. But those wouldn't come from the gir file, those feature flags should be added manually in crate's code, and rebase them.

**Comment by sdroege** [comment]
Yeah, I'd remove them from the gir and add those manually. Both here and in the non-sys crate.

GI unfortunately has no concept of optional API

**Comment by sdroege** [comment]
Oh for changing the .gir, take a look at the `gtk-rs/sys` repo. It has a script to run some XPath expressions over the .gir file.

**Comment by ceyusa** [comment]
> Oh for changing the .gir, take a look at the `gtk-rs/sys` repo. It has a script to run some XPath expressions over the .gir file.

Where? I can't spot any :S

**Comment by sdroege** [comment]
> Where? I can't spot any :S

https://github.com/gtk-rs/gir-files/blob/master/fix.sh

**Comment by ceyusa** [comment]
Just to clarify myself (I'm feeling kind of lost): do you want, instead of commits that modify manually GstGL-1.0.gir, a `fix.sh` script that modifies automatically the gir file?

And that script will do the following:

- [ ] replace the GLFunc record with a  "disguised" one ([already fixed in master](https://cgit.freedesktop.org/gstreamer/gst-plugins-base/commit/gst-libs/gst/gl?id=576564172928a46985466d3a77520337f3613d5e))
- [ ] fix the wrongs enums ([already fixed in master](https://bugzilla.gnome.org/show_bug.cgi?id=797144))
- [ ] remove(?) all the functions with windowing native data type (X11, Wayland, EGL)

**Comment by sdroege** [comment]
Yes, exactly that :) Thanks and sorry for not being more clear

**Comment by ceyusa** [comment]
I guess we can close this issue :)
