### ISSUE TITLE
Wrong signature for GstBaseSrcClass create/alloc & GstBaseTransform transform_ip

### ISSUE THREAD

**Issue by sdroege** [sdroege/gstreamer-sys#3]
https://github.com/sdroege/gstreamer-sys/blob/8b735ff536f096070735416c22d42153d272c06e/gstreamer-base-sys/src/lib.rs#L157-L158

These should be `*mut *mut GstBuffer`

**Comment by sdroege** [comment]
See here https://github.com/GStreamer/gstreamer/blob/0c614a0bd3f228ea252ffd4db4190c0f3af3becc/libs/gst/base/gstbasesrc.h#L225-L230

@epashkin Any ideas what goes wrong there?

**Comment by EPashkin** [comment]
Seems `rustify_pointers` gone wrong as gir file look almost normal (where will be problem on non-sys generation, but currently we don't support closure fields anyway).
```
            <parameter name="buf" transfer-ownership="none">
              <type name="Gst.Buffer" c:type="GstBuffer**"/>
            </parameter>
```

**Comment by sdroege** [comment]
> where will be problem on non-sys generation, but currently we don't support closure fields anyway

These are virtual methods :) Once Federico is further with the macro stuff, we will want to generate generic trampolines for them somehow and callers for the parent class' implementation

**Comment by sdroege** [comment]
With proper annotations it looks like
```xml
          <parameter name="buf"
                     direction="out"                                            
                     caller-allocates="0"
                     transfer-ownership="full">
            <type name="Gst.Buffer" c:type="GstBuffer**"/>
          </parameter>
```

gir still doesn't handle it correctly though (for the -sys bindings, for the non-sys it of course doesn't because of missing support)

**Comment by sdroege** [comment]
This is now tracked at https://gitlab.freedesktop.org/gstreamer/gstreamer-rs-sys/issues/3
